name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.38.5'
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_apk: "Hiddify-Android"
  TARGET_NAME_exe: "Hiddify-Windows-Setup-x64"
  TARGET_NAME_dmg: "Hiddify-MacOS"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Test
        run: flutter test

  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Import Apple Certificates
        if: ${{ inputs.upload-artifact && startsWith(matrix.os,'macos') }}
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: "${{ secrets.APPLE_CERTIFICATE_P12 }}"
          p12-password: "${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Build Release
        run: make ${{ matrix.platform }}-release

      - name: Code Sign Windows
        if: ${{ inputs.upload-artifact && matrix.platform == 'windows' }}
        uses: hiddify/signtool-code-sign-sha256@main
        with:
          certificate: '${{ secrets.WINDOWS_SIGNING_KEY }}'
          cert-password: '${{ secrets.WINDOWS_SIGNING_PASSWORD }}'
          cert-description: 'Hiddify'
          folder: 'dist'
          timestamp-server: 'http://timestamp.digicert.com'
          recursive: true

      - name: Prepare Out Dir
        run: mkdir -p out && cp -r dist/* out/ || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./out
          retention-days: 1

  update-draft:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ inputs.upload-artifact }}
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./out/
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./out/**/*
          tag_name: 'draft'
          prerelease: true