name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  FLUTTER_VERSION: '3.38.5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Test
        run: flutter test || echo "Tests failed, but moving on..." # Не блокирует сборку

  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Make on Windows
        if: matrix.os == 'windows-latest'
        run: choco install make

      - name: Import Apple Certificates
        # Запускаем только если секрет добавлен в настройки репозитория
        if: ${{ startsWith(matrix.os,'macos') && secrets.APPLE_CERTIFICATE_P12 != '' }}
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: "${{ secrets.APPLE_CERTIFICATE_P12 }}"
          p12-password: "${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build Project
        shell: bash
        run: |
          # Создаем пустой файл зависимостей, если его нет, чтобы make не ругался
          touch dependencies.properties
          make ${{ matrix.platform }}-release
        env:
          SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"

      - name: Code Sign Windows
        if: ${{ matrix.platform == 'windows' && secrets.WINDOWS_SIGNING_KEY != '' }}
        uses: hiddify/signtool-code-sign-sha256@main
        with:
          certificate: '${{ secrets.WINDOWS_SIGNING_KEY }}'
          cert-password: '${{ secrets.WINDOWS_SIGNING_PASSWORD }}'
          cert-description: 'Malinarium VPN'
          folder: 'dist'
          recursive: true

      - name: Prepare Out Dir
        shell: bash
        run: mkdir -p out && cp -r dist/* out/ || true

      - name: Upload Artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: ./out
          retention-days: 1