name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
  push:
    branches:
      - main
      - dev
      - new-design-v2 
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: write
      actions: write
      pull-requests: write
      id-token: write
    if: "${{!contains(github.event.head_commit.message, 'release: version')}}"
    with:
      upload-artifact: ${{ github.event_name == 'push' }}